### ISSUE TITLE
Student can filter his mini-assignments by categories

### ISSUE THREAD

**Issue by sergiodxa** [codeableorg/Codeable.app#35]
**As a** user Carlos, 

**I want to** send the solutions of my mini-assignments,

**So that** I can verify that I have solved it correctly.

**Scenarios**

- **I get showed the mini-assignments of a category**

    When I click a category-button

    Then I get showed a the mini-assignments that corresponds to that category

Information

Categories : Sent - New - Saved

**Comment by KattyaCuevas** [comment]
Filters: Today, Completed, Pending, Rejected
